title: Kipkurui Mutai # your name (or website title) here
logo: "/images/pp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I make insights out of data. 
  <br><br>
  I apply data science techniques, such as machine learning, statistical modeling, and artificial intelligence to cleaned data. 
  <br><br>
  <a href="https://www.linkedin.com/in/kipkurui-mutai-3169301a7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
